name: ci

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cat /proc/cpuinfo
      - run: dmidecode
      - run: /usr/bin/systemd-detect-virt
